# -*- mode: ruby -*-
# vim: set ft=ruby :

home = ENV["HOME"]
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :boxlab5 => {
    :box_name => "centos/7",
    :box_version => "1804.02",
    :disks => {
      :sata1 => {
        :dfile => File.join(home, "VirtualMachine/box-lab5/lab5disk1.vdi"),
        :size => 100,
        :port => 1
      }
	}
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.box_check_update = false
      box.vm.host_name = boxname.to_s

      box.vm.provider :virtualbox do |vb|
        vb.name = "box-lab5"
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        needsController = false
        boxconfig[:disks].each do |dname, dconf|
          unless File.exist?(dconf[:dfile])
            vb.customize ["createhd", "--filename", dconf[:dfile], "--variant", "Fixed", "--size", dconf[:size]]
            needsController =  true
          end
        end
        if needsController == true
          vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
          boxconfig[:disks].each do |dname, dconf|
            vb.customize ["storageattach", :id,  "--storagectl", "SATA", "--port", dconf[:port], "--device", 0, "--type", "hdd", "--medium", dconf[:dfile]]
          end
        end
      end

      box.vm.provision "shell", inline: <<-SHELL
        sudo timedatectl set-timezone Europe/Moscow
        sudo yum install vim-enhanced mailx -y
        echo "Install and Start Parsenginxlog Script..."
        sudo cp /vagrant/parsenginxlog /etc/cron.hourly/ && /etc/cron.hourly/parsenginxlog
      SHELL

    end
  end
end
